### ISSUE TITLE
[7] 서비스

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#222]
#### 서비스란

> 파드는 컨트롤러가 관리하므로 한군데에 고정해서 실행되지 않고 클러스터 안을 옮겨 다닌다. 이 과정에서 노드를 옮기면서 실행되기도 하고 클러스터 안 파드의 IP가 변경되기 된다. 이런 환경에서 고정적으로 접근할 때 사용하는 방법이 서비스이다.

#### 서비스 타입

- ClusterIP : 클러스터 안 노드나 파드에서는 클러스터 IP를 이용해서 서비스에 연결된 파드에 접근합니다. 클러스터 외부에서 사용 x

- NodePort : 서비스 하나에 모든 노드의 지정된 포트를 할당/ 노드에 지정된 포트로 접근하므로 클러스터 외부에서도 접근할 수 있음.

- LoadBalancer : 클라우드에서 제공하는 로드밸런서와 파드를 연결한 후 클러스터 외부에서 접근가능

- ExternalName: 클러스터 안에서 외부에 접근할 때 이용

  

#### 서비스 설정
서비스 설정 전에 연결할 파드를 실행시켜야 서비스와 파드가 연결된다.

```yaml
spec:
  type: ClusterIp
  selector:
       app: myApp
   ports:
      - protocol: TCP
         port: 80
         targetPort: 9376
```

- Type  = 서비스 타입
- selector 서비스와 연결할 파드에 설정한 .labels 필드값
- Ports[] 서비스에서 한꺼번에 포트 여러개를 오픈할 경우를 대비해 배열로 선언

```yaml
spec:
  type: NodePort
  selector:
       app: myApp
   ports:
      - protocol: TCP
         port: 80
         targetPort: 9376
         nodePort: 30080
```
- nodePort 30080이 클러스터 Ip 80서비스 포트와 연결되어 외부에서 바로 30080으로 접근가능하다

```yaml
spec:
  type: LoadBalancer
  selector:
       app: myApp
   ports:
      - protocol: TCP
         port: 80
         targetPort: 9376
         nodePort: 30080
```
- loadBalancer로 설정할 경우 external-ip가 설정되고, 실제 외부에서 접근할 수 있게된다.
```yaml
spec:
  type: ExternalName
  externalName: google.com
```
- externalName은 외부에 연결할 도메인 이름이 지정되고,  ExternalName 서비스의 내부도메인에 curl요청을 보내면 cname값인 google.com을 반환한다.
- 참고 https://dev.plusblog.co.kr/30

#### 헤드리스 서비스
- 클러스터 IP가 없는 서비스/ 로드밸런싱이 필요없거나 단일 서비스 IP가 필요 없을 때 사용한다. 
- 셀렉터를 설정해야 파드를 확인할 수 있는 엔드포인트가 만들어진다.
- 클러스터 IP가 없으므로 서비스에 연동된 파드를 직접 가리키는 A레코드 생성된다.

#### kube-proxy
- 쿠버네티스에서 서비스를 만들었을 때 클러스터 IP나 노드포트로 접근할  수 있게 만들어 실제 조작을 하는 컴포넌트

##### userspace
- 클러스터  IP 서비스가 가진 iptables을 거쳐 서비스 kube-proxy가 요청받고 적절한 파드로 연결한다.

##### iptables
- kube-proxy가 iptables관리하는 역할만 하고 실제 트래픽을 받지않는다.
- user-space모드는 파드 하나로의 견결요청이 실패하면 자동으로 다른 파드에 연결한다
- iptables은 파드 하나로의 연결요청이 실패하면 재시도 하지 않는다.

##### ipvs
- 데이터 구조를 해시 테이블로 저장
- iptables 모드보다 빠르고 좋은 성능을 가짐/ 더 많은 로드밸런싱 알고리즘을 가진다.
