### ISSUE TITLE
[8] 인그레스

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#224]
# 8. 인그레스

## 인그레스 개념

인그레스 : 클러스터 외부에서 안으로 접근하는 요청 명세

인그레스 컨트롤러 : 명세에 따라 실제 동작

```yaml
## ingress-basic.yaml
## kubectl apply -f ingress-basic.yml 로 클러스터에 적용
## kubectl describe ingress [인그레스이름] 으로 결과 확인
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    nginx.ingress.kubernates.io/rewrite-target: / ## 리다이렉트 경로 설정
spec:
  rules: ## 규칙 설정 필드 시작
  - host: foo.bar.com
    http:
      paths: ## http 요청을 설정
      - path: /foo1
        backend:
          serviceName: s1
          servicePort: 80 ## s1 서비스의 80포트로 보낸다
      - path: /bars2
        backend:
          serviceName: s2
          servicePort: 80
  - host: bar.foo.com
    http:
      paths:
      - backend:
          serviceName: s2
          servicePort: 80
```

<br/>

## Ingress-nginx 컨트롤러

설치

`git clone https://github.com/kubernates/ingress-nginx.git`

`cd ingrss-nginx/deploy/baremetal`

`kubectl create namespace ingress-nginx` :arrow_left: 컨트롤러 네임 스페이스 지정

`kubectl apply -k .`

컨트롤러 사용 준비 끝.

<br/>

별도의 인그레스 설정이 없을 때 규칙이 설정되어있지 않기 때문에 `404 not found`와 같은 에러 메세지가 나타난다.

```yaml
## 6.3.1/6-2 nginx-deployment 
## deployment-nginx.yaml
## kubectl apply -f deployment-nginx.yaml 로 실행
## kubectl get deploy,rs,rc,pods 로 확인
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx-deployment
    template:
      metadata:
        labels:
          app: nginx-deployment
      spec: 
        containers:
        - name: nginx-deployment
          image: nginx
          ports:
          - containerPort: 80
```

위 디프로이먼트를 인그레스에 연결한다.

`kubectl expose deploy nginx-deployment --name s1` :arrow_left: s1 서비스에 nginx-deployment 디플로이먼트의 서비스를 연결

127.0.0.1 foo.bar.com 을 /etc/hosts 에 추가한다.

http://foo.bar.com:30401/foo1 에 접근하여 확인한다.

<img src="https://user-images.githubusercontent.com/13347548/121815984-fcf41900-ccb3-11eb-912c-7a7575b92ffc.png" alt="image" style="zoom:50%;" />

<br/>

## 인그레스 SSL 설정하기

인그레스에 SSL 인증서를 설정하면 하위 파드에는 설정할 필요가 없고 인그레스만 주기적으로 업데이트해주면 된다.

<img src="https://user-images.githubusercontent.com/13347548/121815976-ee0d6680-ccb3-11eb-97ab-0477a57430a1.png" alt="image" style="zoom:50%;" />

ingrss-nginx 디렉터리보다 상위 디렉터리에서 ssl 디렉터리를 생성하고 명령어를 실행해서 tls.key, tls.crt 파일 생성한다.

`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN-javabom.com"`

<img src="https://user-images.githubusercontent.com/13347548/121816090-8dcaf480-ccb4-11eb-851e-182e9e797d0d.png" alt="image" style="zoom:33%;" />

key, crt 파일을 이용해서 인증서용 시크릿을 생성한다.

`kubectl create secret tls javabom-secret --key tls.key --cert tls.crt`

`kubectl describe secret javabom-secret` 명령어로 인증서 확인

```yaml
## ingress-ssl.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ssl
spec:
  tls:
  - hosts:
    - javabom.com ## 호스트네임 설정
      secretName: javabom-secret ## 시크릿 이름 설정
  rules: ## 규칙 설정 필드 시작
  - host: javabom.com
    http:
      paths: ## http 요청을 설정
      - path: /
        backend:
          serviceName: s1
          servicePort: 80 ## s1 서비스의 80포트로 보낸다
```

`kubectl apply -f ingress.yaml` 로 실행

`127.0.0.1 javabom.com /etc/hosts` 에 추가

`kubectl get svc -n ingress-nginx` 인그레스 컨트롤러에 접근하려고 설정한 NodePort 타입 서비스 상태 확인해서 443 포트로 포트포워딩 된 포트 확인해서 `curl -vI -k https://javabom.com:[포트포워딩포트]/` 로 인증서 적용 확인

<br/>

## 무중단 배포를 할 때 주의할 점

노드에 v1 파드가 실행중일 때 v2 파드를 실행후 v2 파드가 readinessProbe 에서 OK 응답을 보내면 트래픽을 보낸다.

<img src="https://user-images.githubusercontent.com/13347548/121816376-3037a780-ccb6-11eb-9a46-32f9e7fd551a.png" alt="image" style="zoom:50%;" />

파드 관리 설정을 RollingUpdate 로 설정한 경우 `.maxSurge`, `.maxUnavailable` 필드 값을 모두 0으로 설정하면 안된다.

- maxSurge: 기본 파드유지 갯수에서 `+a` 할 수 있는 개수를 설정
  - ex) `.spec.strategy.rollingUpdate.maxSurge: 25%` :arrow_left: 기본 파드 개수의 25%를 추가로 생성할 수 있다.
- maxUnavailable: 디플로이 업데이트 중 이용 못해도 되는 파드의 개수
  - ex) `.spec.strategy.rollingUpdate.maxUnavilable: 25%`

readinessProbe 를 지원하기 어려운 상황이라면 `.spec.minReadySeconds` 로 비슷하게 흉내낼 수 있다.

- minReadySeconds: 설정한 시간 만큼 트래픽을 받지 않는다.
  - 초기화 시간이 긴 컨테이너인 경우에 사용하면 좋다.
  - readinessProbe가 끝나면 무시하고 트래픽을 전송한다.

<br/>

### 쿠버네티스와 컨테이너 안에 그레이스풀 종료 설정

graceful shutdown(그레이스풀 종료): 무중단 배포시 SIGTERM 신호를 받으면 기존 요청만 받고 신규 요청은 받지 않는 것

- SIGTERM: 15번, 정상종료 시그널
- SIGKILL: 9번, 강제종료 시그널

SIGTERM 전송 후 대기시간 내 그레이스 풀 종료가 되지 않으면 SIGKILL 해버린다.

대기시간은 `.terminationGracePeriodSeconds`로 설정한다. 기본 값은 30초

그런데 파드, 프레임 워크, 언어 레벨에서 graceful shutdown을 지원하지 않는 경우 prestop hook을 이용해야한다.

<img src="https://user-images.githubusercontent.com/13347548/121816632-ae487e00-ccb7-11eb-8825-fadb24a1b36c.png" alt="image" style="zoom:50%;" />
