### ISSUE TITLE
[10] 컨피그맵

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#226]
## 컨피그맵

**컨피그맵** : 컨테이너에 필요한 환경 설정을 컨테이너와 분리해서 제공하는 기능

- 컨피그맵으로 컨테이너 하나를 개발용, 스테이지용, 상용 서비스용으로 사용 가능

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-dev
  namespace: default
data:
  DB_URL: localhost
  DB_USER: myuser
  DB_PASS: mypass
  DEBUG_INFO: debug
```

> kubectl apply -f {configmap명}.yaml 으로 적용

### 사용방법

1. 컨피그맵 설정 중 일부만 사용

   ```yaml
   apiVersion: apps/v1
   # 생략
       spec:
         containers:
         - name: testapp
           image: arisu1000/simple-container-app:latest
           ports:
           - containerPort: 8080
           env:
             - name: DEBUG_LEVEL
               valueFrom:
                 configMapKeyRef:
                    name: config-dev
                    key: DEBUG_INFO
   ---
   # 생략
   ```

   - DEBUG_LEVEL 로 환경설정 변수값 설정
   - valueFrom 과 configMapKeyRef 로 컨피그맵과 가져올 키를 지정

2. 컨피그맵 설정 전체 사용

   ```yaml
   apiVersion: apps/v1
   # 생략
       spec:
         containers:
         - name: testapp
           image: arisu1000/simple-container-app:latest
           ports:
           - containerPort: 8080
           envFrom:
           - configMapRef:
               name: config-dev
   #생략
   ```

   - envFrom 과 configMapRef로 어떤 컨피그맵을 가져올지 지정

3. 컨피그맵을 볼륨에 불러와서 사용

   ```yaml
   apiVersion: apps/v1
   #생략
       spec:
         containers:
         - name: testapp
           image: arisu1000/simple-container-app:latest
           ports:
           - containerPort: 8080
           volumeMounts:
           - name: config-volume
             mountPath: /etc/config
         volumes:
         - name: config-volume
           configMap:
             name: config-dev
   #생략
   ```

   - 컨테이너의 볼륨 형식으로 컨피그맵을 설정해서 파일로 컨테이너에 제공 가능
   - config-volume 이라는 볼륨을 만들어서 지정한 컨피그맵의 .data 를 기반으로 파일을 생성
     - DB_URL파일이고 내용은 localhost
