### ISSUE TITLE
[11] 시크릿

### ISSUE THREAD

**Issue by jyami-kim** [Java-Bom/ReadingRecord#227]
### 시크릿

내장 시크릿 : 쿠버네티스 클러스터 안에서 쿠버네티스 API에 접근할 때 사용

- ServiceAccount라는 계정을 생성하면 자동으로 관련 시크릿을 만들고, 이 시크릿으로 해당 ServiceAccount가 사용 권한을 갖는 API에 접근할 수 있다.

사용자 정의 시크릿 : 사용자가 만든 시크릿

```
kubectl create secret generic [시크릿 이름] --from-file=./username.txt --from-file=./password.txt
```

필드 값은 내가 지정한 문구 그대로가 아니라 base64 문자 인코딩 방식이다.

### 시크릿의 type 필드

- Opaque : 기본값. 키-값 형식으로 임의의 데이터를 설정할 수 있음
- kubernetes.io/service-account-token: 쿠버네티스 인증 토큰을 저장함
- kubernetes.io/dockerconfigjson : 도커 저장소 인증 정보를 저장함
- kubernetes.io/tls : TLS 인증서를 저장함

.data.username, .data.password 필드값 설정시 주의할 점 : base 64 문자 인코딩값을 설정해야함

#### 1. 파드의 환경 변수로 시크릿 사용하기

```yaml
env:
- name : SERCRET_USERNAME
  valueFrom:
    secretKeyRef:
      name: user-pass-yaml
      key: username
```

#### 2. 볼륨 형식으로 파드에 시크릿 제공하기

```yaml
containers:
  - name: testapp
    volumeMounts:
    - name: volume-secret
      mountPath: "/etc/volume-secret"
      readOnly: true
  volumes:
  - name: volume-secret
  	secret:
  		secretName: user-pass-yaml
```

시크릿 설정의 필드가 컨테이너 안에 파일로 저장

#### 3. 프라이빗 컨테이너 이미지를 가져올 때 시크릿 사용하기

인증정보를 시크릿에 설정해 저장한 후 사용한다

```
kubectl create secret docker-registry [시크릿 이름]
```

.type 필드값은 kubernetes.io/dockerconfigjson 이다

```yaml
containers:
- name: testapp
  imagePullSecrets:
  - name : dockersecret
```

#### 4. 시크릿으로 TLS 인증서를 저장해 사용하기

```
kubectl create secret tls [시크릿 이름] --key tls.key --cert tls.crt
```

type 필드값은 kubernetes.io/tls 이다

이 시크릿을 인그레스와 연결해서 사용할 수 있다.

### 시크릿 데이터 용량 제한

시크릿 데이터는 etcd에 암호화하지 않은 텍스트로 저장된다. 개별 시크릿 데이터의 최대 용량은 1MB이다.

etcd에는 중요한 데이터가 많으므로 접근제한을 걸도록하자. 보통 etcd 관련 명령을 사용하는 API 통신에 TLS 인증이 적용되어있으므로 인증서가 잇는 사용자만 etcd에 접근해 관련 명령을 사용할 수 있다.

계정 기반이나 IP 기반 접근 제어 등으로 제한한다.
