### ISSUE TITLE
[12] 파드 스케줄링

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#228]
### 12. 파드 스케줄링

> 파드를 어떤 노드에 실행할 것인지에 관한 다양한 옵션이 있다. 옵션을 조합하면 사용자가 원하는 구조대로 클러스터 안에 파드 배치가 가능하게된다.

- 노드셀렉터

  - 파드가 실행될 노드를 선택하는 기능 - 노드의 레이블에 설정된 값으로 노드를 선택한다.

  - 노드 셀렉터 사용법

    ```sh
    kubectl label nodes docker-desktop disktype=ssd
    ```

    ```yaml
    apiVersion: v1
        kind: Pod
        metadata:
               name: kubernetes-nodeselector-pod
      spec:
      	containers:
      	   - name: kubernetes-nodeselector-pod
      	   	 image: arisu1000/simple-container-app:latest
      	   	 ports:
      	   	 	- containerPort: 8080
      	   	 nodeSelector:
      	   	 	disktype: ssd
    ```

    node label에 disktype = ssd값을 추가한 후 pod 시행 설정에 nodeSelector에 disktype ssd를 설정한 후 실행하면 된다 

- 노드 어피니티

  - 노드 셀렉터와 비슷하게 노드 레이블 기반으로 파드 스케줄링을 진행한다. 
  - 노드 어피니티와 노드셀렉터의 조건을 모두 만족하는 노드에 파드를 스케줄링한다.
    - requiredDuringSchedulingIgnoredDuringExecution - 스케줄링하는 동안 꼭 필요한 조건
      - 노드 라벨의 값과 파드 실행 yml에 설정한 어피니티 조건에 일치해야만 동작
    - preferredDuringSchedulingIgnoredDuringExecution - 스케줄링하는 동안 만족하면 좋은 조건
      - weight은 1~100까지 설정 가능하며 여러 조건이 맞을때 weight가 더해진다.
      - 노드 별로 weight 합산이 가장 큰 노드에서 pod를 실행한다.
      - 만약 조건 만족하는 노드가 하나도 없을때는 파드는 실행된다. 
    - 두 필드는 실행 중에 조건이 바뀌어도 무시한다
    - [affinity operator](https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node/) 설정방법은 해당 문서 참고

- 파드의 어피니티와 안티 어피니티

  - 디플로이먼트나 스테이트풀 세트로 파드를 배포했을 때 개별 파드사이의 관계를 정의하는 용도다

    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: redis-cache
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
       		 - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - store
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis-server
        image: redis:3.2-alpine
    ```

    - labels app 필드값이 store인 파드가 속한 노드를 피해서 파드를 추가한다는 설정이다.
    - podAffinity를 사용한다면 pod에 해당 label이 있는 경우에 같이 실행한다

- 테이트와 톨러레이션

  - 테인트는 특정노드에 설정할 수 있고, 테인트가 설정된 노드는 파드들을 스케줄링하지 않는다.
  - 테인트를 성정한 노드에 파드들을 스케줄링하려면 툴러레이션을 설정해야한다.
  - 테인트와 톨러레이션은 주로 노드를 특정 역할만 하도록 만들때 사용한다. (DB 등)

- 커든과 드레인

  - 특정 노드에 있는 파드들을 모두 다른 노드로 옮기거나 특정 노드에 파드들을 스케줄링하지 않도록 제한할때 사용한다.

  - kubectl cordon 명령은 추가로 파드를 스케줄링하지 않도록 합니다.

  - 드레인은 지정된 노드에서 다른노드로 파드들을 이동시킬때 사용한다.
