### ISSUE TITLE
[13] 인증과 권한 관리

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#229]
# 13. 인증과 권한 관리

쿠버네티스 API 접근 포트는 기본 6443이고 TLS 인증이 적용되어 있다. kubectl을 이용해서 아무런 인증없이 사용할 수 있는 이유는 .kube 디렉토리에 있는 config 파일에 인증 정보가 있기 때문이다.

쿠버네티스 계정은 사용자 계정과 쿠버네티스가 관리하는 서비스 계정으로 분류된다.

```yaml
apiVersion: v1
clusters: ## 클러스터 관련 필드
- cluster:
    insecure-skip-tls-verify: true ## true -> 인증서가 공인 기관 인증서인지 확인한다.
    server: https://localhost:6443
  name: docker-desktop-cluster
context: ## 사용자, 네임스페이스 연결 
- context:
    cluster: docker-desktop-cluster
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop  ## context 필드가 여러개 일때
kind: Config
preferences: {}
users: ## 클러스터를 사용할 사용자 그룹
- name: docker-desktop
  user: 
    client-certificate-data: sdfasdfasdf
    client-key-data: asdfasdfas
```

위 인증을 TLS 인증이 아닌 서비스 계정을 이용한 인증을 하기 위해선

1. 서비스 계정 확인
   - kubectl get serviceaccount
2. 서비스 계정에 연결된 시크릿 확인
   - kubectl get serviceaccount [service 계정이름] -o yaml
   - .secret.name 필드에 시크릿 이름 확인
3. 시크릿 상세 내용을 확인
   - kubectl describe secret [시크릿이름]
   - Data 항목의 token 값을 확인

```yaml
apiVersion: v1
clusters: 
- cluster:
    insecure-skip-tls-verify: true 
    server: https://localhost:6443
  name: docker-desktop-cluster
context: 
- context:
    cluster: docker-desktop-cluster
    user: [서비스 계정 이름]
  name: docker-desktop
current-context: docker-desktop  
kind: Config
preferences: {}
users: 
- name: docker-desktop
  user: 
    client-certificate-data: sdfasdfasdf
    client-key-data: asdfasdfas
- name: [서비스 계정 이름]
  user:
  token: [Data 항목에서 확인한 token 값]
```

kubectl get pods --v=7 로 디버깅을 통해 적용 확인

## 권한관리

1. 접근할 수 있는 사용자인지 인증
2. 사용자가 API 사용권한이 있는지 확인

따라서 권한을 부여해야하는데 권한을 부여하는 방식은 ABAC, RBAC가 있다. ABAC는 잘 안쓰고 RBAC를 사용한다.

### RBAC (Role-based access control)

- 사용자와 역할을 별개로 선언후 두 가지를 조합하여 사용자에게 권한 부여
- 마스터에 접근할 필요가 없음
  - kubectl, API 를 이용해 관리

#### 롤

- 특정 API, 자원 사용 권한을 명시해둔 규칙의 집합

종류

- 일반 롤
  - 일반 롤이 속한 네임스페이스
  - 어느 네임스페이스에 속하지 않은 자원, API
  - 노드 사용권한
  - 헬스체크용 URL 엔드포인트
- 클러스터 롤
  - 클러스터 전체 사용권한을 관리

##### 일반롤

```yaml
kind: Role ## 롤을 의미
apiVersion: rbac.authorization.k8s.io/v1 ## RBAC 권한 관리
metadata:
  namespace: default ## 롤이 속할 네임스페이스
  name: read-role ## 롤의 이름
rules: ## 롤에서 허용할 규칙
- apiGroups: [""] ## API
  resources: ["pods"] ## 자원
  resourceNames: ["[특정파드이름]"] ## 옵셔널한 필드 전체 파드가 아닌 특정파에만 롤을 적용한다. 하지만 verbs는 적용되지 않는다.
  verbs: ["get", "list"] ## 동작
```

적용: kubectl apply -f read-role.yaml

##### 클러스터 롤

일반 롤 설정의 네임스페이스 필드가 존재하지 않는다.

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-aggregation
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
    kubernetes.io/bootstrapping: rbac-defaults
rules: []
```

- .aggregationRule 필드를 이용해서 다른 클러스터 롤을 조합할 수 있다.
- 자원이 아닌 URL 형식으로 규칙을 설정할 수 있다.

```yaml
rules:
- nonResourceURLs: ["/healthcheck", "/metrics/*"]
  verbs: ["get", "list"]
```

### 롤 바인딩

- 롤과 사용자를 묶는 역할
- 종류 
  - 롤 바인딩: 특정 네임스페이스 하나에 적용
  - 클러스터 롤 바인딩: 클러스터 전체에 적용

#### 롤 바인딩

```yaml
## 사용자 설정
apiVersion: v1
kind: ServiceAccount ## 서비스 계정을 의미
metadata:
  name: myuser ## 사용자 이름
  namespace: default 
```

```yaml
## 롤 바인딩 설정
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: ## 롤 바인딩에 대한 설정
  name: read-rolebinding
  namespace: default
subject:  ## 사용자 연결
- kind: ServiceAccount
  name: myuser
  apiGroup: ""  ## 핵심 API 그룹으로 설정했다는 의미
roleRef:  ## 롤 연결
  kind: Role
  name: read-role
  apiGroup: rbac.authorization.k8s.io
```

#### 클러스터 롤 바인딩

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read:clusterrolebinding
subject:
- kind: ServiceAccount
  name: myuser
  namespace: default ## 서비스가 특정 네임스페이스에 한정되기 때문에 어느 네임스페이스에 속해 있는지 명시해준다.
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: read-clusterrole
  apiGroup: rbac.authorization.k8s.io
```

#### 롤, 롤바인딩 / 클러스터 롤, 클러스터 롤 바인딩의 관례

![image](https://user-images.githubusercontent.com/13347548/126895537-f2fc289a-c7b7-4d15-938e-beddb0e59ec5.png)
