### ISSUE TITLE
[14]  데이터저장

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#230]
### 볼륨(Volume)

컨테이너를 종료하거나 재시작할 때 데이터가 유지될 수 있도록 하는 저장소를 의미하는 오브젝트 

**별도의 볼륨 플러그인 사용**
- 클라우드 기반(aws~, azure~, gcp~로 시작되는 플러그인)
- 오픈소스 스토리지 서비스(glusterfs, cephfs)
- 쿠버네티스 내부 오브젝트(zjsvlzmaoq, tlzmflt) 
- 컨테이너 노드의 디스크를 직접 사용
- NFS: 하나의 컨테이너에 볼륨을 붙여서 NFS 서버로 설정 

**볼륨관련한 설정필드** 

`.spec.container.volumeMounts.mountPropagation`: 같은 파드, 또는 노드 내의 컨테이너들끼리 볼륨을 공유할지에 대한 설정

- None(기본필드값): 해당 컨테이너에서 마운트 된 디렉토리의 서브디렉토리 마운트는 볼 수 없음. 
- HostToContainer: 해당 볼륨하위에 마운트된 다른 볼륨도 볼 수 있음 
- Bidirectional: 하위에 마운트된 디렉터리도 볼 수 있고(HostToContainers), 호스트 안 다른 컨테이너나 파드에서도 같은 볼륨을 사용할 수 있음 

#### emptyDir

디스크를 임시로 컨테이너에 볼륨으로 할당해서 사용. 파드가 사라지면 함께 사라짐. 

<u>컨테이너가 재시작되어도 파드는 살아있기 때문에 데이터를 유지할 수 있음.</u> 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts: # 선언한 볼륨을 마운트 
    - mountPath: /cache # 디렉토리 지정 
      name: cache-volume # 볼륨명
  volumes: # 사용하려는 볼륨 선언 
  - name: cache-volume
    emptyDir: {} 
```

#### hostPath

호스트에 있는 실제 파일이나 디렉터리 마운트 

파드를 재시작해도 호스트에 데이터가 남음.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # 호스트의 디렉터리 위치
      path: /data
      # 이 필드는 선택 사항이다
      type: Directory # 설정한 경로에 디렉터리가 존재해야함. 존재하지 않으면 ContainerCreating 상태 유지, p.334
```

#### nfs

여러개 파드에서 볼륨 하나를 공유해 읽기/쓰기를 동시에 할 때 사용.

동시에 접근할 수 있는 안정성 높은 외부 스토리지를 볼륨으로 설정하고 해당 파드에 NFS 서버 설정한 뒤 마운트. 

외부볼륨과 통신할 NFS Server deployment.yaml

```yaml
 spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: # nfserver image
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd # NFS 서버에서 사용하는 프로세스.
          containerPort: 20048 
        - name: rpcbind # NFS 서버에서 사용하는 프로세스.  
          containerPort: 20048 
       securityContext: # 컨테이너의 보안설정
       	  privileged: true # 모든 호스트 장치에 접근 가
       volumeMounts:
        - mountPath: /exports # 마운트할 디렉터리
          name: hostpath-vol # 일반적으로는 외부볼륨 지정
```

NFS server 를 사용할 pod deployment.yaml

```yaml
volumeMounts:
    - mountPath: /test-nfs
      name: nfs-vol
  volumes:
  - name: nfs-vol
    nfs:
      server: # nfs server의 ip
      path: /
```

### 퍼시스턴트 볼륨과 퍼시스턴트 볼륨 클레임

PV(PersistentVolume): 볼륨 그 자체 '자원' 명시

PVC(PersistentVolumeClaim): 사용자가 PV 에 하는 요청. 파드와 PV 를 직접 연결하지 않고 PVC 를 거치기 때문에 어떤 스토리지를 사용하든 상관없게된다.

**퍼시스턴트 생명주기**
![image](https://user-images.githubusercontent.com/47847993/127759517-db6896bd-2ff8-4e26-b3d4-936a06ea1dc7.png)

**프로비저닝**

PV 를 만드는 단계 

- 미리 만들어두는 static 방법
  - 스토리지 용량에 제한이 있을 때 사용함녀 유용 
- 요청이 오면 만드는 dynamic 방법
  - StoragleClass 로 PV 생성 

**바인딩**

PV를 PVC 와 연결. 원하는 PV 가 있을 때까지 대기하다가 바인딩됨. 1:1 바인딩

**사용**

PVC 는 파드에 설정되고 파드는 PVC 를 볼륨으로 인식하고 사용.

사용 중인 PVC는 임의로 삭제될 수 없음(Storage Object in Use Protection)

**반환**

사용이 끝난 PVC 가 삭제되고 PV 를 초기화(Reclaim)하는 과정.

초기화정책

- Retain: PV 보존. PVC 삭제 이후의 PV 는 해제 상태이기 떄문에 직접 초기화 과정을 걸쳐야함.
- Delete: PV 를 삭제하고 연결된 외부 스토리지 볼륨도 제거. 동적 프로비저닝의 기본 정책. 
- Recycle: PV 데이터를 삭제하고 다시 새로운 PVC 에서 해당 PV 를 사용할 수 있도록 함. 
  - **경고:** `Recycle` 반환 정책은 더 이상 사용하지 않는다. 대신 권장되는 방식은 동적 프로비저닝을 사용하는 것

### 퍼시스턴트 볼륨 템플릿

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  release: stable # (optional) PV, PVC 모두 쿠버네티스 자원이므로 레이블로도 매칭 가능 
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem # 일부 스토리지는 raw(block storage)도 가능 
  accessModes: # 볼륨의 읽기/쓰기 모드 
    - ReadWriteOnce # 노드 하나에만 읽기/쓰기 하도록 마운트 가능 (p. 345)
  persistentVolumeReclaimPolicy: Recycle # PV 해제시 초기화 옵션 
  storageClassName: slow # 해당 스토리지 클래스에 맞는 PVC 와 연결
  mountOptions: # 추가옵션 지정이 가능한 볼륨 플러그인에서 사용. 
    - hard
    - nfsvers=4.1
  nfs: # 볼륨 플러그인
    path: /tmp
    server: 172.17.0.2
```

### 퍼시스턴트 볼륨 클레임 템플릿

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi # 자원을 얼마나 요청할 것안지. PV를 초과하면 바운딩 불가. 
  storageClassName: slow # PV 에서 지정한 storageClassName 
  	- allowVolumeExpansion: true # 일부 볼륨 플러그인에서 사용가능한 PVC 옵션을 늘릴 수 있는 옵션(p. 352)
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
```

### 파드에서 PVC 사용하기

```yaml
volumeMounts:
    - mountPath: "tmp"
      name: myvolume
  volumes:
  - name: myvolume
		persistentVolumeClaim:
			claimName: myclaim
```
