### ISSUE TITLE
[18] HPA

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#235]
## HPA(Horizontal Pod Autoscaler)

파드를 <u>CPU 사용량 기반</u>으로 오토스케일링하는 Object
![image](https://user-images.githubusercontent.com/47847993/131853417-49df1a39-dec1-4969-abf4-6dcd428ae5f0.png)

**모니터링 기본 반복시간**
```sh
--horizontal-pod-autoscaler-sync-period # default 30sec
```

**쿨 다운 지연시간 옵션**

```sh
--horizontal-pod-autoscaler-downscale-delay # default 5min
```

**오토스케일링 파드 수 기준**

```
대상 파드 갯수 = (현재 파드의 CPU 사용률을 모두 더한 값/목표 CPU 사용률)을 올림한 값
```

## HPA 설정

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache # 오토스케일링 지정 Pod name
  minReplicas: 1 # 최소 pod
  maxReplicas: 10 # 최대 pod
  targetCPUUtilizationPercentage: 30 # 30% 이상을 사용하면 오토스케일링 
```

<u>동일한 CLI</u>

```sh
kubectl autoscale deployment php-apache --cpu-percent=30 --min=1 --nax=10
```

*주의해야할 점*

`kubectl top pods`가 정상적으로 pod 의 메트릭을 보여주는데`kubectl get hpa`의 cpu 가 &lt;unknown&gt; 이면 deployment 설정에 `.spec.template.containers[].resources.request.cpu` 필드 값이 빠진건 아닌지 확인해야 함
