### ISSUE TITLE
[21] 헬름

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#237]
## 헬름

- 헬름 : 쿠버네티스의 템플릿들의 집합(**차트**)을 관리하는 패키지 매니저 도구
  - 차트 저장소(chart repository)와 연결해 쿠버네티스 클러스터에 차트를 설치하거나 삭제 가능
  - 헬름 차트들의 배포 주기를 관리할 수 있음
  - MySQL, Redis, Jenkins 등 여러 애플리케이션을 쉽게 설치하고 관리 가능
- 차트(chart) : 쿠버네티스에서 실행할 애플리케이션을 만드는데 필요한 정보 묶음
- 컨피그(config) : 패키지한 차트에 넣어서 배포 가능한 오브젝트를 만들 때 사용할 수 있는 설정
- 릴리즈(release) : 특정 컨피그를 이용해 실행 중인 차트의 인스턴스

### 헬름 클라이언트, 틸러 서버

- 헬름은 헬름 클라이언트와 쿠버네티스 API와 통신하는 틸러 서버로 구성
- 헬름 클라이언트를 사용해 로컬 서버에서 차트를 만들고 저장소를 관리
- 틸러 서버와 통신해 쿠버네티스 클러스터에 설치하려는 차트를 보낼 수 있음
  - 현재 클러스터에 실행 중인 애플리케이션 릴리즈 정보를 요청하거나 업그레이드, 삭제 요청 등을 틸러 서버로 보냄

### 헬름 차트의 구조

- 차트는 디렉터리 하나에 포함된 파일들의 집합

  ```
  wordpress/
    Chart.yaml          # 차트에 대한 정보를 가진 YAML 파일
    LICENSE             # 옵션: 차트의 라이센스 정보를 가진 텍스트 파일
    README.md           # 옵션: README 파일
    values.yaml         # 차트에 대한 기본 환경설정 값들
    values.schema.json  # 옵션: values.yaml 파일의 구조를 제약하는 JSON 파일
    charts/             # 이 차트에 종속된 차트들을 포함하는 디렉터리
    crds/               # 커스텀 자원에 대한 정의
    templates/          # values와 결합될 때, 유효한 쿠버네티스 manifest 파일들이 생성될 템플릿들의 디렉터리
    templates/NOTES.txt # 옵션: 간단한 사용법을 포함하는 텍스트 파일
  ```

- Chart.yaml

  ```yaml
  apiVersion: 차트 API 버전 (필수)
  name: 차트명 (필수)
  version: SemVer 2 버전 (필수)
  kubeVersion: 호환되는 쿠버네티스 버전의 SemVer 범위 (선택)
  description: 이 프로젝트에 대한 간략한 설명 (선택)
  type: 차트 타입 (선택)
  keywords:
    - 이 프로젝트에 대한 키워드 리스트 (선택)
  home: 프로젝트 홈페이지의 URL (선택)
  sources:
    - 이 프로젝트의 소스코드 URL 리스트 (선택)
  dependencies: # 차트 필요조건들의 리스트 (optional)
    - name: 차트명 (nginx)
      version: 차트의 버전 ("1.2.3")
      repository: 저장소 URL ("https://example.com/charts") 또는 ("@repo-name")
      condition: (선택) 차트들의 활성/비활성을 결정하는 boolean 값을 만드는 yaml 경로 (예시: subchart1.enabled)
      tags: # (선택)
        - 활성화 / 비활성을 함께하기 위해 차트들을 그룹화 할 수 있는 태그들
      enabled: (선택) 차트가 로드될수 있는지 결정하는 boolean
      import-values: # (선택)
        - ImportValues 는 가져올 상위 키에 대한 소스 값의 맵핑을 보유한다. 각 항목은 문자열이거나 하위 / 상위 하위 목록 항목 쌍일 수 있다.
      alias: (선택) 차트에 대한 별명으로 사용된다. 같은 차트를 여러번 추가해야할때 유용하다.
  maintainers: # (선택)
    - name: maintainer들의 이름 (각 maintainer마다 필수)
      email: maintainer들의 email (각 maintainer마다 선택)
      url: maintainer에 대한 URL (각 maintainer마다 선택)
  icon: 아이콘으로 사용될 SVG나 PNG 이미지 URL (선택)
  appVersion: 이 앱의 버전 (선택). SemVer인 필요는 없다.
  deprecated: 차트의 deprecated 여부 (선택, boolean)
  annotations:
    example: 키로 매핑된 주석들의 리스트 (선택).
  ```

  > semver 2 : 유의적 버저닝 https://semver.org/lang/ko/

### 헬름 차트 저장소

- 차트 뮤지엄 : 오픈 소스 차트 저장소
  - 차트 저장소 역할을 하므로 실행할 때 차트를 저장할 스토리지를 지정해야함, 다양한 클라우드 저장소를 사용할 수 있음
  - S3, 구글 클라우드 스토리지 등

[​헬름 DOCS](https://helm.sh/ko/docs/ )
